### ISSUE TITLE
Error after docker-compose up

### ISSUE THREAD

**Issue by frepke** [containeroo/Traefik-examples#3]
Thanks for your great examples, unfortunately I'm getting the next error with docker-compose up.
How can I solve this?

_kr.,
Frepke_

------------------

**docker-compose up**
Creating network "nextcloud-fpm_default" with the default driver
Creating nextcloud-mariadb ... done
Creating nextcloud-redis   ... done
Creating nextcloud-fpm     ... done
Creating nextcloud-cron    ... 
Creating nextcloud-nginx   ... 
Creating nextcloud-cron    ... done
ERROR: for nextcloud-nginx  a bytes-like object is required, not 'str'

ERROR: for nextcloud-nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.22/containers/34615212bfe3bb6c0fc2529b99e3e693dacb36a144d5d27353dea750a1d7bba2/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("b'OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/opt/containers/nextcloud-fpm/nginx/nginx.conf\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/5345c4f36d5d96b2153bd4c1eaa7f4166fbfe89e9c99b276ecc81b09d427e96a/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/5345c4f36d5d96b2153bd4c1eaa7f4166fbfe89e9c99b276ecc81b09d427e96a/merged/etc/nginx/nginx.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[25698] Failed to execute script docker-compose

**Comment by containeroo-gists** [comment]
Hello Frepke

I forgot to upload the `nginx.conf`.
Please delete the folder `nginx/nginx.conf`, download the `nginx.conf` and move it into the `nginx` folder.

**Comment by frepke** [comment]
Hello,

Thanks for your answer.
I can't see the nginx.conf yet, but I'll use it when it's uploaded.

kr.,
Frepke

**Comment by frepke** [comment]
Yes, this is a way better.
thanks
